### ISSUE TITLE
Inaccessible demo :-/

### ISSUE THREAD

**Issue by mathieucaroff** [elstr/user-management#1]
When opening the demo https://users-management-icxjcxesnl.now.sh I get:

> This deployment is not available anymore.
>
> ZEIT Now 1.0 is being shut down. As part of this, all ZEIT Now 1.0 Deployments will become inaccessible.
>
> If you are the owner of this ZEIT Now 1.0 Project, [click here to learn more →](https://mailchi.mp/f923e55efe1d/simplified-pricing-1087517)

**Comment by elstr** [comment]
well.. this is a pretty old project hahaha and ZEIT Now 1.0 has been shot down so I should update the version and also could refactor this code to react 16
